services:
  - type: web
    name: shanbalik-bot
    runtime: python
    pythonVersion: "3.11.9"
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn bot:app --host 0.0.0.0 --port $PORT